export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';

export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';

export const ADD_STUDENT_MEETING_SUCCESS = 'ADD_STUDENT_MEETING_SUCCESS';

export const UPDATE_STUDENT_MEETING_SUCCESS = 'UPDATE_STUDENT_MEETING_SUCCESS';
export const UPDATE_PATIENT_MEETING_SUCCESS = 'UPDATE_PATIENT_MEETING_SUCCESS';

export const SHOW_NOTICE_MESSAGE = 'SHOW_NOTICE_MESSAGE';
export const HIDE_NOTICE_MESSAGE = 'HIDE_NOTICE_MESSAGE';

export const SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT';

export const SET_EDITABLE_STUDENT_MEETING = 'SET_EDITABLE_STUDENT_MEETING';

export const SET_EDITABLE_PATIENT_MEETING = 'SET_EDITABLE_PATIENT_MEETING';
